Fixed Makefile and validating each execution

diff --git a/ubuntu/installer b/ubuntu/installer
--- a/ubuntu/installer
+++ b/ubuntu/installer
@@ -1,6 +1,12 @@
 #!/usr/bin/env bash
 
 cp .zshrc ~/
+if [ ! -d "$HOME/.config/dconf" ]; then
+  echo "Creating dconf"
+  mkdir ~/.config/dconf
+fi
+
+cp user ~/.config/dconf
 
 if [ ! -d "$HOME/Development/" ]; then
   mkdir ~/Development/
@@ -14,6 +20,11 @@ installer_run() {
   install_sh="./$1"
   if chmod +x "$install_sh"; then
     sh "$install_sh"
+    if [ $? -ne "0" ]; then
+        echo "Failed to run command $install_sh"
+      else
+        echo "$install_sh executed"
+    fi
   fi
 }
 
@@ -22,12 +33,5 @@ grep -E '^[^\s#]' <runner.conf | while IFS= read -r line; do
 done
 
 rm -Rf ~/.config-temp
-
-if [ ! -d "$HOME/.config/dconf" ]; then
-  echo "Creating dconf"
-  mkdir ~/.config/dconf
-fi
-
-cp user ~/.config/dconf
 
 exec zsh -l
